frameworks/dradis_framework.md

Hey Team, here we are, many thanks for putting this together! 👏

Dradis Framework - collaboration and reporting for teams

---

mobile_hacking/androidtamer.md

adding androidtamer

---

mobile_hacking/mobsf.md
webapp_security/zap.md

Pull request

---

cryptography/hashview.md

Here is the pull request for the tool Hashview. Let me know if there's anything i missed.

Pull Request for Tool: Hashview

---

mobile_hacking/badintent.md

Adding BadIntent:
https://www.blackhat.com/us-17/arsenal/schedule/#badintent---integrating-android-with-burp-8044
https://github.com/mateuszk87/BadIntent

badintent description

---

hardening/lynis.md

This is the initial markdown file for the Lynis project.

Initial for Lynis (security auditing and hardening)

---

mobile_hacking/kwetza.md

Adding kwetza md according to template

Adding kwetza md

---

exploitation/rattler.md

adding rattler md according to template

Adding rattler md

---

webapp_security/jack.md

Adding Jack md

---

network_attacks/eaphammer.md

Adding EAPHammer

---

forensics/inVtero.net.md

invtero.net.md

---

network_defense/sweetsecurity.md

Adding Sweet Security

---

network_defense/sitch.md

chg: usr: Added sitch.md

---

red_team/shinobot.md

Add ShinoBOT.md in Red Team

---

mobile_hacking/objection.md

Add objection

---

hardware_iot/WHID.md

Being presented @ BHEU on 7th of December

Add WHID Injector

---

frameworks/evilgrade.md
vulnerability_assessment/faraday.md

New tool: Faraday

---

frameworks/evilgrade.md

You are missing the 2010 Black Hat:
http://www.blackhat.com/html/bh-us-10/bh-us-10-specialevents_arsenal.html

New tool: Evilgrade

---

network_defense/cs-suite.md

Presented at BlackHat Europe Arsenal 2017

Added Cloud Security Suite to Network Defense

---

ics_scada/dyode.md

Hey !
I just added the description for my DYODE project, hoping not to be too late :)

Add DYODE project

---

osint/trape.md

One of the most popular tools of OSINT at the moment, the cause of the evolution of the phishing attacks

trape OSINT tool

---

vulnerability_assessment/archery.md

Open Source Vulnerability Assessment and Management helps developers and pentesters to perform scans and manage vulnerabilities.

New Tool: Archery

---

vulnerability_assessment/intrigue.md

let me know if anything's missing here!

add an entry for intrigue

---

webapp_security/wssat.md

WSSAT 2.0 released

---

malware_research/floss.md

I've added the Asia session and updated the badges. Can you please check the reference at https://github.com/toolswatch/badges/blob/master/README.md? I had some issues with the documented links and resources.

Floss update

---

code_assessment/owasp_dependency_check.md

OWASP dependency-check

---

webapp_security/ThreatPlaybook.md

ThreatPlaybook has been selected at BlackHat Arsenal this year. It should also be included in the `Vulnerability Assessment` Category

ThreatPlaybook Init Description

---

vulnerability_assessment/trommel.md

Add trommel.md to be uploaded to vulnerability_assessment section
I followed formatting template but let me know if there are any problems.

Add trommel.md to be uploaded to vulnerability_assessment section

---

osint/trape.md

The project I handle it mainly myself. And right now the version 2.0 has been issued. Thanks!

Main changes of trape

---

malware_research/malboxes.md

Sorry for the delay and a submission so close to the 2019 edition :sweat_smile:

Added Malboxes' 2017 entry to the repository

---

frameworks/cyber_range.md

Adding Cyber Range to the toolswatch repo

---

red_team/circo.md

Added circo.md

---

reverse_engineering/packet_sender.md

Session: 
https://www.blackhat.com/us-21/arsenal/schedule/index.html#packet-sender-24082

Add Packet Sender to Black Hat Arsenal Tools

---

vulnerability_assessment/remote_method_guesser.md

Added the tool remote-method-guesser presented at BHUSA Arsenal 2021.

Add remote-method-guesser

---

hardware_iot/emba.md

From Black Hat Arsenal USA 2022 and Asia 2022

EMBA - Embedded Analyzer

---

network_defense/js_api.md

Added my tool
https://www.blackhat.com/us-22/arsenal/schedule/#protecting-your-crypto-asset-against-malicious-js-phishing-27713

Add js api

---

cloud/AWSGoat.md
cloud/AzureGoat.md

Adding AWSGoat and AzureGoat

---

malware_research/DotDumper.md
malware_research/Libra's Binary Analysis Course.md
malware_research/m3.md

As presented in 2021 and 2022, these tools can now be added into this repository to complete the overview.

Addition of DotDumper, m3, and my Binary Analysis Course

---

code_assessment/betterscan.md

Hi,
Propose to add Betterscan.
Betterscan was presented in 2 Arsenal sessions on Black Hat 2022 MEA Arsenals.
Thanks,

Adding Betterscan

---

frameworks/exegol.md

Hi, this PR adds Exegol which was presented at BH Europe 2022's Arsenal, thanks!

Adding Exegol

---

hardware_iot/emba.md

EMBA update - BHEU22

---

malware_research/Shoggoth.md

Hi, this PR adds Shoggoth which was presented at BH Europe 2022's Arsenal. Thanks in advance!

Adding Shoggoth

---

red_team/scmkit.md

Adding SCMKit from Black Hat USA Arsenal 2022

Adding SCMKit

---

vulnerability_assessment/blackdagger.md

I want to add the MD file with the description and code of our tool Blackdagger.

Added Blackdagger tool
